# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: liminal devblog
email: karl.astrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is not an awesome description but I couldn't really stand having
  the default placeholder description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liminal.github.io" # the base hostname & protocol for your site
twitter_username: randomkarl
github_username:  liminal

# Build settings
markdown: kramdown
